[package]
name = "aoc"
version = "2.0.19"
authors = ["Harm te Hennepe <dhtehennepe@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1"
petgraph = "0.4"
itertools = "0.8"
bytecount = "0.6.0"
