[package]
name = "aoc"
version = "2.0.20"
authors = ["Harm te Hennepe <dhtehennepe@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
itertools = "0.9.0"
regex = "1"
num_enum = "0.5.1"
